// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var UrlParse = require("url-parse");

var Internal = /* module */[];

function parse(base, path) {
  if (base !== undefined) {
    return new UrlParse(path, base, false);
  } else {
    return new UrlParse(path, false);
  }
}

function stringify(url) {
  return url.toString();
}

exports.Internal = Internal;
exports.parse = parse;
exports.stringify = stringify;
/* url-parse Not a pure module */
