// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var UrlParse = require("url-parse");

var Internal = /* module */[];

function parse(base, path) {
  if (base !== undefined) {
    return new UrlParse(path, base, false);
  } else {
    return new UrlParse(path, false);
  }
}

exports.Internal = Internal;
exports.parse = parse;
/* url-parse Not a pure module */
